/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;
import UserInterface.AdminRole.ManageSalesperson;
import Business.*;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import UserInterface.AdminRole.SupplierWorkAreaJPanel;
import UserInterface.SalePerson.SalesPersonWorkAreaJPanel;
import UserInterface.SupplierRole.ManageProductCatalog;
/**
 *
 * @author james
 */
public class LoginArea extends javax.swing.JPanel {

    /**
     * Creates new form LoginArea
     */
    private JPanel userProcessContainer;
    private Business business;
    private SupplierDirectory supplierDirectory;
    private SalesPersonCatalog salesPersonCatalog;

    LoginArea(JPanel userProcessContainer, Business business) {
       initComponents();
        this.userProcessContainer=userProcessContainer;
        this.business=business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loginBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        unTF = new javax.swing.JTextField();
        passPF = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("UserID:");

        jLabel2.setText("Password:");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel3.setText("Login");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(loginBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(unTF)
                            .addComponent(passPF, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(309, 309, 309))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(324, 324, 324)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(unTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(loginBtn)
                .addGap(108, 108, 108))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
                    
                      
                         if((!passPF.getText().isEmpty())&&((!unTF.getText().isEmpty())))
                         {
                      if((passPF.getText().equals(business.getPassword()))&&(unTF.getText().equals(business.getID())))
                        {
                              ManageArea ma=new ManageArea(userProcessContainer,business);           
                           userProcessContainer.add("ManageArea",ma);
                           CardLayout layout=(CardLayout)userProcessContainer.getLayout();
                           layout.next(userProcessContainer);
                          }
                      if(business.getSupplier(unTF.getText(), passPF.getText())!=null)
                     
                      { ManageProductCatalog mpc =new ManageProductCatalog(userProcessContainer, business,business.getSupplier(unTF.getText(), passPF.getText()));
                      userProcessContainer.add("SupplierWorkAreaJPanel",mpc);
                           CardLayout layout=(CardLayout)userProcessContainer.getLayout();
                           layout.next(userProcessContainer);
                      }   
                          
                     if(business.getSalesperson(unTF.getText(), passPF.getText())!=null)
                           {
                               SalesPersonWorkAreaJPanel spwaj =new SalesPersonWorkAreaJPanel(userProcessContainer, business,business.getSalesperson(unTF.getText(), passPF.getText()));
                                userProcessContainer.add(" SalesPersonWorkAreaJPanel",spwaj);
                           CardLayout layout=(CardLayout)userProcessContainer.getLayout();
                           layout.show(userProcessContainer," SalesPersonWorkAreaJPanel");
                           }
                               
                         }
                         else  {JOptionPane.showMessageDialog(null,"Not enter data");}
    }//GEN-LAST:event_loginBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passPF;
    private javax.swing.JTextField unTF;
    // End of variables declaration//GEN-END:variables
}
