/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SupplierRole;

import Business.Business;
import Business.Market;
import Business.MarketOffer;
import Business.Product;
import Business.Supplier;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author wuyue
 */
public class CreateNewProductJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewProductJPanel
     */
    JPanel userProcessContainer;
    Supplier supplier;
    Business business;
    Market market;
    CreateNewProductJPanel(JPanel userProcessContainer, Supplier supplier, Business business) {
         initComponents();
        this.userProcessContainer = userProcessContainer;
        this.supplier = supplier;
        this.business=business;
        market=new Market();
    }
     public boolean validation(String ProdName,double ceilingPrice,double TargetPrice,double FloorPrice){
         Pattern p1 = Pattern.compile("^[A-Za-z]+$");
        Matcher m1 = p1.matcher(ProdName);
        boolean a = true;
        for(Supplier supplier:business.getSupplierDirectory().getSupplierlist()){
            for(Product p : supplier.getProductCatalog().getProductcatalog()){
            if(txtName.getText().equals(p.getProdName())){
                a = false;
            }
        }
        }
        boolean flag1 = m1.matches() & a;
        if(!a){
            JOptionPane.showMessageDialog(null,"Product you added already exist!");
        }
        if(!m1.matches()){
            JOptionPane.showMessageDialog(null,"User Name should be composed of uppercase or lowercase letters!");
        }
        
        Pattern p2 = Pattern.compile("^[0-9]+\\.?[0-9]{0,9}$");
        Matcher m2 = p2.matcher(Double.toString(ceilingPrice));
        boolean flag2 = m2.matches();
        //System.out.println(flag2);
        if(!flag2){
            JOptionPane.showMessageDialog(null,"Price should be positive number");
        }
        
        Pattern p3 = Pattern.compile("^[0-9]+\\.?[0-9]{0,9}$");
        Matcher m3 = p3.matcher(Double.toString(ceilingPrice));
        boolean flag3 = m3.matches();
        if(!flag3){
            JOptionPane.showMessageDialog(null,"Price should be positive number");
        }
        
        Pattern p4 = Pattern.compile("^[0-9]+\\.?[0-9]{0,9}$");
        Matcher m4 = p4.matcher(Double.toString(ceilingPrice));
        boolean flag4 = m4.matches();
        if(!flag4){
            JOptionPane.showMessageDialog(null,"Price should be positive number");
        }   
        boolean flag5=false;
        if((ceilingPrice>TargetPrice)&&(TargetPrice>
                FloorPrice)){
            flag5=true;
        }
        if(!flag5){
            JOptionPane.showMessageDialog(null,"CelingPrice>targetPrice>floorPrice");
        }
         return flag1&flag2&flag3&flag4&flag5;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        cpriceTF = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        QtyTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TargetTF = new javax.swing.JTextField();
        floorTF = new javax.swing.JTextField();

        jLabel1.setText("Create New Product");

        jLabel2.setText("Product Name:");

        jLabel3.setText("Product ID:");

        jLabel4.setText("CeilingPrice: ");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtId.setEnabled(false);

        btnAdd.setText("Add Product");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel5.setText("Quantity:");

        jLabel6.setText("TargetPrice:");

        jLabel7.setText("FloorPrice:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnBack)))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(txtId)
                            .addComponent(cpriceTF)
                            .addComponent(TargetTF))
                        .addComponent(QtyTF, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(floorTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(196, 236, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addGap(185, 185, 185))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnBack))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cpriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TargetTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(floorTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QtyTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(35, 35, 35)
                .addComponent(btnAdd)
                .addContainerGap(157, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
         String stringPrice = cpriceTF.getText();
           if(stringPrice.isEmpty()==false){    
        boolean validation=validation(txtName.getText(), 
                Double.parseDouble(cpriceTF.getText()),Double.parseDouble(TargetTF.getText()),
                Double.parseDouble(floorTF.getText()));
            if(validation){
            double price = Double.parseDouble(stringPrice);
            Product p = new Product();
            p.setProdName(txtName.getText());
            p.setAvail(Integer.parseInt(QtyTF.getText()));
            p.setCeilingPrice(price);
            p.setTargetPrice(Double.parseDouble(TargetTF.getText()));
            p.setFloorPrice(Double.parseDouble(floorTF.getText()));
            supplier.getProductCatalog().getProductcatalog().add(p);
            for(Market market:business.getMarketList().getMarketListcatelog()){
                 MarketOffer marketOffer=new MarketOffer(market, p);
                 business.getMarketOfferCatalog().getMarketOfferList().add(marketOffer);
            }
            JOptionPane.showMessageDialog(null, "Product added!", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
             
        }
        else JOptionPane.showMessageDialog(null, "error", "Info", JOptionPane.INFORMATION_MESSAGE);   
//        Product p = new Product();
//        p.setProdName(txtName.getText());
//        p.setAvail(Integer.parseInt(QtyTF.getText()));
//        String stringPrice = cpriceTF.getText();
//        if(stringPrice.isEmpty()==false){
//            double price = Double.parseDouble(stringPrice);
//            p.setCeilingPrice(price);
//            p.setTargetPrice(Double.parseDouble(TargetTF.getText()));
//            p.setFloorPrice(Double.parseDouble(floorTF.getText()));
//            supplier.getProductCatalog().getProductcatalog().add(p);
//            for(Market market:business.getMarketList().getMarketListcatelog()){
//                 MarketOffer marketOffer=new MarketOffer(market, p);
//                 business.getMarketOfferCatalog().getMarketOfferList().add(marketOffer);
//            }
//
//             JOptionPane.showMessageDialog(null, "Product added!", "Info", JOptionPane.INFORMATION_MESSAGE);
//        }
//        else JOptionPane.showMessageDialog(null, "error", "Info", JOptionPane.INFORMATION_MESSAGE);
//        
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageProductCatalog manageProductCatalog = (ManageProductCatalog) component;
        manageProductCatalog.refreshTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField QtyTF;
    private javax.swing.JTextField TargetTF;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JTextField cpriceTF;
    private javax.swing.JTextField floorTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
